# Generated by Django 6.1.1 on 2026-09-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_course_lesson_assignment_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='correct_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
    ]
