# Generated by Django 6.1.1 on 2026-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_quizquestion_correct_index_quizquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='track',
            field=models.CharField(choices=[('AI & Machine Learning', 'AI & Machine Learning'), ('Robotics', 'Robotics'), ('Cybersecurity', 'Cybersecurity'), ('Internet of Things', 'Internet of Things'), ('Software Development', 'Software Development'), ('Startup Incubation', 'Startup Incubation'), ('UI/UX Design', 'UI/UX Design'), ('Data Science & Analytics', 'Data Science & Analytics'), ('Mobile App Development', 'Mobile App Development'), ('Cloud Computing', 'Cloud Computing'), ('Blockchain & Web3', 'Blockchain & Web3'), ('Game Development', 'Game Development'), ('Digital Marketing & Growth', 'Digital Marketing & Growth'), ('Product Management', 'Product Management'), ('DevOps & Site Reliability', 'DevOps & Site Reliability'), ('AR/VR & Immersive Tech', 'AR/VR & Immersive Tech')], default='cloud', max_length=50),
            preserve_default=False,
        ),
    ]
