# Generated by Django 6.0.7 on 2026-07-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('Next cohort', 'Next cohort'), ('Studio visit', 'Studio visit'), ('partnership', 'Partnership'), ('Teaching / mentoring', 'Teaching / mentoring'), ('Something else', 'Something else')], default='Something else', max_length=50),
        ),
    ]
