# Generated by Django 6.0.7 on 2026-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('track', models.CharField(choices=[('AI & Machine Learning', 'AI & Machine Learning'), ('Robotics', 'Robotics'), ('Cybersecurity', 'Cybersecurity'), ('Software Development', 'Software Development'), ('IoT', 'IoT'), ('Startup Incubation', 'Startup Incubation')], max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
