# Generated by Django 6.0.7 on 2026-08-05 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='track',
            field=models.CharField(choices=[('AI & Machine Learning', 'AI & Machine Learning'), ('Robotics', 'Robotics'), ('Cybersecurity', 'Cybersecurity'), ('Software Development', 'Software Development'), ('IoT', 'IoT'), ('Startup Incubation', 'Startup Incubation'), ('UI/UX Design', 'UI/UX Design'), ('Data Science', 'Data Science'), ('Mobile Dev', 'Mobile Dev'), ('Cloud Computing', 'Cloud Computing'), ('Game Development Lab', 'Game Development Lab'), ('Digital Marketing & Growth', 'Digital Marketing & Growth'), ('Product Management Foundations', 'Product Management Foundations'), ('DevOps & Site Reliability', 'DevOps & Site Reliability'), ('AR/VR & Immersive Tech', 'AR/VR & Immersive Tech')], max_length=50),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('AI & Machine Learning', 'AI & Machine Learning'), ('Robotics', 'Robotics'), ('Cybersecurity', 'Cybersecurity'), ('Software Development', 'Software Development'), ('IoT', 'IoT'), ('Startup Incubation', 'Startup Incubation'), ('UI/UX Design', 'UI/UX Design'), ('Data Science', 'Data Science'), ('Mobile Dev', 'Mobile Dev'), ('Cloud Computing', 'Cloud Computing'), ('Game Development Lab', 'Game Development Lab'), ('Digital Marketing & Growth', 'Digital Marketing & Growth'), ('Product Management Foundations', 'Product Management Foundations'), ('DevOps & Site Reliability', 'DevOps & Site Reliability'), ('AR/VR & Immersive Tech', 'AR/VR & Immersive Tech')], max_length=50)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='user.student')),
            ],
            options={
                'unique_together': {('student', 'track')},
            },
        ),
    ]
