# Generated by Django 6.1.1 on 2026-09-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='track',
            field=models.CharField(blank=True, choices=[('AI & Machine Learning', 'AI & Machine Learning'), ('Robotics', 'Robotics'), ('Cybersecurity', 'Cybersecurity'), ('Internet of Things', 'Internet of Things'), ('Software Development', 'Software Development'), ('Startup Incubation', 'Startup Incubation'), ('UI/UX Design', 'UI/UX Design'), ('Data Science & Analytics', 'Data Science & Analytics'), ('Mobile App Development', 'Mobile App Development'), ('Cloud Computing', 'Cloud Computing'), ('Blockchain & Web3', 'Blockchain & Web3'), ('Game Development', 'Game Development'), ('Digital Marketing & Growth', 'Digital Marketing & Growth'), ('Product Management', 'Product Management'), ('DevOps & Site Reliability', 'DevOps & Site Reliability'), ('AR/VR & Immersive Tech', 'AR/VR & Immersive Tech')], max_length=50),
        ),
    ]
